###################################################
#                                                 #
#    Плагин сделан студией MerzeevaStudios        #
#                                                 #
#    Реквизиты для пожертвования (на чай ☕):     #
#    Карта: 2202 2085 8741 4815                   #
#                                                 #
###################################################

# Основной язык плагина (файл должен быть в папке languages/)
language: ru

# НАСТРОЙКИ ПЕРСОНАЛА И АДМИН-ЧАТА
admin-join-alert:
  enable: true # Включить/выключить приветствие вышки (true/false)
  permission: "merzeeva.admin.alert" # Право для уведомления (по умолчанию OP)

# НАСТРОЙКИ АНТИ-СЛИВА И ЭФФЕКТОВ
cooldowns:
  tempban-seconds: 300 # Задержка на повторный бан (в секундах)
  tempmute-seconds: 60  # Задержка на повторный мут (в секундах)

# Эффекты при выдаче наказаний модератором через меню
effects:
  enable-sound: true # Включить звуки при наказаниях (true/false)
  ban-sound: "ENTITY_LIGHTNING_BOLT_THUNDER" # Звук при бане
  mute-sound: "BLOCK_NOTE_BLOCK_BASS"         # Звук при муте
